version: '3.8'

services:
  app:
    build: .
    ports:
      - "8000:8000"
    environment:
      - DATABASE_URL=mysql+pymysql://user:password@db:3306/balance_one
      - SECRET_KEY=your-secret-key-here
      - REFRESH_SECRET_KEY=your-refresh-secret-key-here
      - ALGORITHM=HS256
      - ACCESS_TOKEN_EXPIRE_MINUTES=30
      - ENVIRONMENT=development
    depends_on:
      - db
    volumes:
      - .:/app
    networks:
      - balance-one-network

  db:
    image: mysql:8.0
    ports:
      - "3306:3306"
    environment:
      - MYSQL_ROOT_PASSWORD=rootpassword
      - MYSQL_DATABASE=balance_one
      - MYSQL_USER=user
      - MYSQL_PASSWORD=password
    volumes:
      - mysql_data:/var/lib/mysql
    networks:
      - balance-one-network

#  phpmyadmin:
#    image: phpmyadmin/phpmyadmin
#    ports:
#      - "8080:80"
#    environment:
#      - PMA_HOST=db
#      - MYSQL_ROOT_PASSWORD=rootpassword
#      - MYSQL_USER=user
#      - MYSQL_PASSWORD=password
#    depends_on:
#      - db
#    networks:
#      - balance-one-network

volumes:
  mysql_data:

networks:
  balance-one-network:
    driver: bridge 