"""Update stock models to use CommonModel

Revision ID: 2d9e859ce0e3
Revises: 6323fd9c3391
Create Date: 2025-04-02 14:43:51.703184

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2d9e859ce0e3'
down_revision: Union[str, None] = '6323fd9c3391'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
