"""Update stock models to use CommonModel

Revision ID: 5a87aaa3a0c2
Revises: d1079e114c2c
Create Date: 2025-04-02 13:59:44.564604

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5a87aaa3a0c2'
down_revision: Union[str, None] = 'd1079e114c2c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('advisory_recommendations', sa.Column('is_active', sa.Boolean(), nullable=True, comment='레코드 활성화 상태'))
    op.add_column('stocks', sa.Column('is_active', sa.Boolean(), nullable=True, comment='레코드 활성화 상태'))
    op.add_column('user_stocks', sa.Column('is_active', sa.Boolean(), nullable=True, comment='레코드 활성화 상태'))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user_stocks', 'is_active')
    op.drop_column('stocks', 'is_active')
    op.drop_column('advisory_recommendations', 'is_active')
    # ### end Alembic commands ###
