"""Add fields to AdvisoryRecommendation

Revision ID: 78176c135f33
Revises: deb8f3228a2a
Create Date: 2025-04-02 16:17:37.665208

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = '78176c135f33'
down_revision: Union[str, None] = 'deb8f3228a2a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('advisory_recommendations', sa.Column('price_at_time', sa.Float(), nullable=False, comment='추천 시점의 주가'))
    op.add_column('advisory_recommendations', sa.Column('total_investment', sa.Float(), nullable=False, comment='총 투자금액'))
    op.add_column('advisory_recommendations', sa.Column('market_cap', sa.Float(), nullable=False, comment='시가총액'))
    op.add_column('advisory_recommendations', sa.Column('change_rate', sa.Float(), nullable=False, comment='등락률'))
    op.add_column('advisory_recommendations', sa.Column('volume', sa.Integer(), nullable=False, comment='거래량'))
    op.alter_column('deposit_withdrawals', 'amount',
               existing_type=mysql.FLOAT(),
               comment='금액 (원화)',
               existing_comment='금액',
               existing_nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('deposit_withdrawals', 'amount',
               existing_type=mysql.FLOAT(),
               comment='금액',
               existing_comment='금액 (원화)',
               existing_nullable=False)
    op.drop_column('advisory_recommendations', 'volume')
    op.drop_column('advisory_recommendations', 'change_rate')
    op.drop_column('advisory_recommendations', 'market_cap')
    op.drop_column('advisory_recommendations', 'total_investment')
    op.drop_column('advisory_recommendations', 'price_at_time')
    # ### end Alembic commands ###
