"""Update stock models to use CommonModel

Revision ID: 7e1e00152504
Revises: 5a87aaa3a0c2
Create Date: 2025-04-02 14:01:13.414271

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7e1e00152504'
down_revision: Union[str, None] = '5a87aaa3a0c2'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('advisory_requests', sa.Column('is_active', sa.Boolean(), nullable=True, comment='레코드 활성화 상태'))
    op.add_column('transactions', sa.Column('is_active', sa.Boolean(), nullable=True, comment='레코드 활성화 상태'))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('transactions', 'is_active')
    op.drop_column('advisory_requests', 'is_active')
    # ### end Alembic commands ###
