"""stock update

Revision ID: d1079e114c2c
Revises: cb025ec3cf26
Create Date: 2025-04-02 13:52:19.722335

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = 'd1079e114c2c'
down_revision: Union[str, None] = 'cb025ec3cf26'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('advisory_requests', 'portfolio_type',
               existing_type=mysql.VARCHAR(length=20),
               type_=sa.Enum('AGGRESSIVE', 'BALANCED', name='portfoliotype'),
               comment='포트폴리오 유형',
               existing_comment='포트폴리오 유형 (공격형/균형형)',
               existing_nullable=False)
    op.add_column('stocks', sa.Column('market_cap', sa.Float(), nullable=False, comment='시가총액'))
    op.add_column('stocks', sa.Column('volume', sa.Integer(), nullable=False, comment='거래량'))
    op.add_column('stocks', sa.Column('high_price', sa.Float(), nullable=False, comment='고가'))
    op.add_column('stocks', sa.Column('low_price', sa.Float(), nullable=False, comment='저가'))
    op.add_column('stocks', sa.Column('open_price', sa.Float(), nullable=False, comment='시가'))
    op.add_column('stocks', sa.Column('prev_close', sa.Float(), nullable=False, comment='전일 종가'))
    op.add_column('stocks', sa.Column('change_rate', sa.Float(), nullable=False, comment='등락률'))
    op.add_column('stocks', sa.Column('change_amount', sa.Float(), nullable=False, comment='등락금액'))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('stocks', 'change_amount')
    op.drop_column('stocks', 'change_rate')
    op.drop_column('stocks', 'prev_close')
    op.drop_column('stocks', 'open_price')
    op.drop_column('stocks', 'low_price')
    op.drop_column('stocks', 'high_price')
    op.drop_column('stocks', 'volume')
    op.drop_column('stocks', 'market_cap')
    op.alter_column('advisory_requests', 'portfolio_type',
               existing_type=sa.Enum('AGGRESSIVE', 'BALANCED', name='portfoliotype'),
               type_=mysql.VARCHAR(length=20),
               comment='포트폴리오 유형 (공격형/균형형)',
               existing_comment='포트폴리오 유형',
               existing_nullable=False)
    # ### end Alembic commands ###
