"""Update user

Revision ID: deb8f3228a2a
Revises: edbe65bac47d
Create Date: 2025-04-02 15:28:38.749186

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'deb8f3228a2a'
down_revision: Union[str, None] = 'edbe65bac47d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('login_attempts',
    sa.Column('user_id', sa.String(length=36), nullable=False, comment='사용자 ID'),
    sa.Column('ip_address', sa.String(length=45), nullable=False, comment='로그인 시도 IP 주소'),
    sa.Column('user_agent', sa.String(length=255), nullable=False, comment='사용자 브라우저/클라이언트 정보'),
    sa.Column('is_successful', sa.Boolean(), nullable=False, comment='로그인 성공 여부'),
    sa.Column('attempt_count', sa.Integer(), nullable=False, comment='연속 시도 횟수'),
    sa.Column('last_attempt_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True, comment='마지막 시도 일시'),
    sa.Column('id', sa.String(length=36), nullable=False, comment='UUID 형식의 고유 식별자'),
    sa.Column('is_active', sa.Boolean(), nullable=True, comment='레코드 활성화 상태'),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True, comment='생성 일시'),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True, comment='수정 일시'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_login_attempts_id'), 'login_attempts', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_login_attempts_id'), table_name='login_attempts')
    op.drop_table('login_attempts')
    # ### end Alembic commands ###
