"""Update deposit

Revision ID: edbe65bac47d
Revises: e3d26c240f60
Create Date: 2025-04-02 14:56:40.092622

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'edbe65bac47d'
down_revision: Union[str, None] = 'e3d26c240f60'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('deposit_withdrawals',
    sa.Column('user_id', sa.String(length=36), nullable=False, comment='사용자 ID'),
    sa.Column('type', sa.Enum('DEPOSIT', 'WITHDRAWAL', name='depositwithdrawaltype'), nullable=False, comment='입출금 유형 (입금/출금)'),
    sa.Column('amount', sa.Float(), nullable=False, comment='금액'),
    sa.Column('status', sa.Enum('PENDING', 'COMPLETED', 'FAILED', 'CANCELLED', name='depositwithdrawalstatus'), nullable=False, comment='입출금 상태'),
    sa.Column('ip_address', sa.String(length=45), nullable=True, comment='입출금 발생 IP 주소'),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True, comment='생성 일시'),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True, comment='수정 일시'),
    sa.Column('id', sa.String(length=36), nullable=False, comment='UUID 형식의 고유 식별자'),
    sa.Column('is_active', sa.Boolean(), nullable=True, comment='레코드 활성화 상태'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_deposit_withdrawals_id'), 'deposit_withdrawals', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_deposit_withdrawals_id'), table_name='deposit_withdrawals')
    op.drop_table('deposit_withdrawals')
    # ### end Alembic commands ###
